name: CI/CD Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build using Make
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@latest

      - name: Install Makefile and GCC compiler
        run: sudo apt install make gcc

      - name: Compile
        run: make
